export const INCREASE_RESOURCES = "INCREASE_RESOURCES";
export const DECREASE_RESOURCES = "DECREASE_RESOURCES";
export const ADD_INCOME_SOURCE = "ADD_INCOME_SOURCE";
export const BUY_UPGRADE = "BUY_UPGRADE";
