export const RESET = 'RESET';

export const INCREASE_RESOURCES = "INCREASE_RESOURCES";
export const DECREASE_RESOURCES = "DECREASE_RESOURCES";

export const ADD_INCOME_SOURCE = "ADD_INCOME_SOURCE";

export const BUY_UPGRADE = "BUY_UPGRADE";

export const ADD_MESSAGE = "ADD_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const TOGGLE_PAUSE = "TOGGLE_PAUSE";
export const PRESTIGE = "PRESTIGE";
export const CLOSE_STORY = "CLOSE_STORY";

// COLONY
export const ADD_BUILDING = "ADD_BUILDING";
export const ADD_COLONIST = "ADD_COLONIST";
export const INCREASE_COLONY_RESOURCE = "INCREASE_COLONY_RESOURCE";
export const DECREASE_COLONY_RESOURCE = "DECREASE_COLONY_RESOURCE";
export const ASSIGN_COLONIST = "ASSIGN_COLONIST";
export const UN_ASSIGN_COLONIST = "UN_ASSIGN_COLONIST";
